[Interface]
# Bouncing = 0
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = 8KSH2YbVTF+1GYsTdA3d7UIUbmqfFQVqVrnvkqBHpWI=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# HK#27-TOR
PublicKey = 69aqlYVoz2XbbnHQi5iglZ3ISvD6HHTWeRAHMrqDPA0=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 156.146.45.139:51820

PersistentKeepalive = 25