[Interface]
# Bouncing = 14
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = 2O6CVgiP23SbzlgTEyYgYhWWhEbPnJph6PPbWb31Bms=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# HK#66
PublicKey = b04WYLiUOie4OkYbneVXdqnmoGKZyU7Vpfb9N+Qf31c=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 156.146.45.129:51820

# Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
# Endpoint = [2a02:6ea0:d60f:2188::10]:51820
PersistentKeepalive = 25