[Interface]
# Bouncing = 0
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = gKJTKss/7uKW187M9Wa3KlFFtiVUgNkwJaS3PvMdEmA=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# SE#31-TOR
PublicKey = jnw7R6t43/63SOFCw9jf6y3a5exG9a+2fcYN3Cir6Qo=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 185.159.156.90:51820

PersistentKeepalive = 25