[Interface]
# Bouncing = 0
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = EF+bLDvUzRGtNe2FBhvZZbc+f3VeuYg9p3QOahJPk1A=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# US-CO#21-TOR
PublicKey = wKzdG/orqK8ZHgBUaIB6RvxjuZvV2s58e+Palmqx1Co=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 84.17.63.17:51820

PersistentKeepalive = 25