[Interface]
# Bouncing = 37
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = mAt3Wjeh9evwhc5SmQinnWGBGlANQL9rsD/rnb3zllU=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# US-DC#99
PublicKey = E4gRP4uJvUMxTXVfTDLtkAmfAV7Jyl1uYltU8tlvb2Y=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 217.138.198.246:51820

PersistentKeepalive = 25