[Interface]
# Bouncing = 8
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = OKDoO4na3cQ8VizVfsuj3rOUHBv3kRqKv1+vB6p55H8=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# US-UT#49
PublicKey = fDSDNxB7yfHbaemo7cAFMWBsEm31bVAAradL4hbBEG0=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 74.63.204.210:51820

# Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
# Endpoint = [2607:ff68:6:d::10]:51820
PersistentKeepalive = 25