[Interface]
# Bouncing = 3
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = MAAR/2qbSruYZ7/KxXNVNacWg9p6CPj/nno6+VOgdWQ=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# US-FREE#33
PublicKey = SOXFyakZ9HI9TeiMRyMoy3PXYEzJJ/IDJcMvxZ3uWSE=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 149.102.254.90:51820

PersistentKeepalive = 25