[Interface]
# Bouncing = 1
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = 4IkIXi8zJQE789GPix0WtiasXw+0vOTk9jItGcck2no=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# US-FREE#94
PublicKey = 0t8cQ6GkwX1CYTO8AuIwDjbBZKYFrYZjEDqkUNCBAzQ=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 149.22.80.114:51820

PersistentKeepalive = 25